### ISSUE TITLE
xmlrunner fails to install on Python 3.12

### ISSUE THREAD

**Issue by rob-spoor** [pycontribs/xmlrunner#14]
When I try to install xmlrunner through pip on Python 3.12 (Dockerized), I get the following error:
```
4.770 Collecting xmlrunner
4.781   Downloading xmlrunner-1.7.7.tar.gz (5.6 kB)
4.790   Preparing metadata (setup.py): started
5.074   Preparing metadata (setup.py): finished with status 'error'
5.093   error: subprocess-exited-with-error
5.093
5.093   × python setup.py egg_info did not run successfully.
5.093   │ exit code: 1
5.093   ╰─> [17 lines of output]
5.093       Traceback (most recent call last):
5.093         File "/tmp/pip-install-i0yuvyyb/xmlrunner_38e90a448b434bd4a1231cd932df7852/xmlrunner/xmlrunner.py", line 13, in <module>
5.093           from unittest2.runner import TextTestRunner
5.093       ModuleNotFoundError: No module named 'unittest2'
5.093
5.093       During handling of the above exception, another exception occurred:
5.093
5.093       Traceback (most recent call last):
5.093         File "<string>", line 2, in <module>
5.093         File "<pip-setuptools-caller>", line 34, in <module>
5.093         File "/tmp/pip-install-i0yuvyyb/xmlrunner_38e90a448b434bd4a1231cd932df7852/setup.py", line 6, in <module>
5.093           from xmlrunner.version import __version__
5.093         File "/tmp/pip-install-i0yuvyyb/xmlrunner_38e90a448b434bd4a1231cd932df7852/xmlrunner/__init__.py", line 3, in <module>
5.093           from .xmlrunner import XMLTestRunner
5.093         File "/tmp/pip-install-i0yuvyyb/xmlrunner_38e90a448b434bd4a1231cd932df7852/xmlrunner/xmlrunner.py", line 17, in <module>
5.093           from unittest import TestResult, _TextTestResult, TextTestRunner
5.093       ImportError: cannot import name '_TextTestResult' from 'unittest' (/usr/local/lib/python3.12/unittest/__init__.py). Did you mean: 'TextTestResult'?
5.093       [end of output]
5.093
5.093   note: This error originates from a subprocess, and is likely not a problem with pip.
5.096 error: metadata-generation-failed
```
The issue seems to be on this line: https://github.com/pycontribs/xmlrunner/blob/74ae6a3c2395dd103be05b8feb9838608dd5a6e8/xmlrunner/xmlrunner.py#L17C1-L18C1

**Comment by ssbarnea** [comment]
Yes, the project can be considered dead by now. I am planning to archive the project. Already removed xmlrunner dependency from jira project few minutes ago.

**Comment by rob-spoor** [comment]
I found https://github.com/xmlrunner/unittest-xml-reporting/ which is compatible, at least for my needs.
