### ISSUE TITLE
Crashing with UnicodeEncodeError when exceptions have special characters

### ISSUE THREAD

**Issue by calinmarina** [pycontribs/xmlrunner#7]
crashes when some test fails with message that contains special characters:

this is where it crashes... instead of showing the error it shows the stacktrace of the xmlrunner:

```
======================================================================
ERROR [135.328s]: test_FEAT_PWD_CPLX_007_allSpecialChars_2 (feature_PasswordComplexity.feature_PasswordComplexity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runTestList.py", line 28, in <module>
    xmlrunner.XMLTestRunner(verbosity=2, output="../test-reports", stream=sys.stdout).run(suite)
  File "/home/automation_tests_pyenv/lib/python2.7/site-packages/xmlrunner/xmlrunner.py", line 421, in run
    result.printErrors()
  File "/home/automation_tests_pyenv/lib/python2.7/site-packages/unittest2/runner.py", line 116, in printErrors
    self.printErrorList('ERROR', self.errors)
  File "/home/automation_tests_pyenv/lib/python2.7/site-packages/xmlrunner/xmlrunner.py", line 221, in printErrorList
    self.stream.writeln('%s' % test_info.get_error_info())
  File "/home/automation_tests_pyenv/lib/python2.7/site-packages/unittest2/runner.py", line 32, in writeln
    self.write(arg)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 251: ordinal not in range(128)
```

Setup:

``` bash
$uname -a
Linux servername 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$pip list
unittest-xml-reporting (1.14.0)
unittest2 (1.1.0)
xmlrunner (1.7.7)
$echo $LANG
en_GB.UTF-8
```
##

**Comment by calinmarina** [comment]
I solved it by changing line 211 in xmlrunner.py from:

``` python
self.stream.writeln('%s' % test_info.get_error_info())
```

to:

``` python
self.stream.writeln('%s' % test_info.get_error_info().encode('ascii', 'ignore').decode('ascii'))
```

here's the result... the special characters are not breaking the XML generation anymore:

``````
test_FEAT_PWD_CPLX_007_allSpecialChars_2 (feature_PasswordComplexity.feature_PasswordComplexity) ... FAIL (161.408s)

======================================================================
ERROR [161.408s]: test_FEAT_PWD_CPLX_007_allSpecialChars_2 (feature_PasswordComplexity.feature_PasswordComplexity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/tests/src/feature_PasswordComplexity.py", line 68, in test_FEAT_PWD_CPLX_007_allSpecialChars_2
    self.tryPassConfirmEnabled('9:;<=>?@YZ_a",?')
  File "/home/jenkins/workspace/tests/src/feature_PasswordComplexity.py", line 119, in tryPassConfirmEnabled
    self.wrapup_when_exception()```
``````

**Comment by ssbarnea** [comment]
See https://github.com/pycontribs/xmlrunner/issues/10 or make a PR.
